// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRT-bLEmADyw0s7lb9-XfBjNB5Kgnt024',
    appId: '1:1006887131547:android:50cd668a1b656ddbd6e93e',
    messagingSenderId: '1006887131547',
    projectId: 'flutter-ecommerce-bloc-734b4',
    storageBucket: 'flutter-ecommerce-bloc-734b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSusC6up9Ja86OAkxzGmO1Lof4MOUogBU',
    appId: '1:1006887131547:ios:a2696555001b0c69d6e93e',
    messagingSenderId: '1006887131547',
    projectId: 'flutter-ecommerce-bloc-734b4',
    storageBucket: 'flutter-ecommerce-bloc-734b4.appspot.com',
    iosClientId: '1006887131547-3g819un6t030ksq9u6pc3ca6bb6iesbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceBloc',
  );
}
